<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_aboutfull',
		'title' => 'AboutFull',
		'fields' => array (
			array (
				'key' => 'field_53c6d80c76c73',
				'label' => 'Author',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53c6d81a76c74',
				'label' => 'Author Name',
				'name' => 'author_name',
				'type' => 'text',
				'instructions' => 'Add author name.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53c6d83376c75',
				'label' => 'Author Position',
				'name' => 'author_position',
				'type' => 'text',
				'instructions' => 'Add author position or proffesion.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53c6d84a76c76',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5412ce673a8a4',
				'label' => 'Slider Animation',
				'name' => 'slider_animation',
				'type' => 'select',
				'instructions' => 'Choose Slider Animation.',
				'choices' => array (
					'fxSoftScale' => 'SoftScale',
					'fxPressAway' => 'PressAway',
					'fxSideSwing' => 'SideSwing',
					'fxFortuneWheel' => 'FortuneWheel',
					'fxSwipe' => 'Swipe',
					'fxPushReveal' => 'PushReveal',
					'fxSnapIn' => 'SnapIn',
					'fxLetMeIn' => 'LetMeIn',
					'fxStickIt' => 'StickIt',
					'fxArchiveMe' => 'ArchiveMe',
					'fxVGrowth' => 'VGrowth',
					'fxSlideBehind' => 'SlideBehind',
					'fxSoftPulse' => 'SoftPulse',
					'fxEarthquake' => 'Earthquake',
					'fxCliffDiving' => 'CliffDiving',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5412e1b31a4cc',
				'label' => 'Autoplay Duration',
				'name' => 'autoplay_duration',
				'type' => 'number',
				'instructions' => 'Select slider autoplay duration.',
				'default_value' => 0,
				'placeholder' => 0,
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53c6d87176c78',
				'label' => 'Slider',
				'name' => 'slider',
				'type' => 'repeater',
				'instructions' => 'Add slider images.',
				'sub_fields' => array (
					array (
						'key' => 'field_53c6d88576c79',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add image.',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_aboutFull.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_aboutme',
		'title' => 'AboutMe',
		'fields' => array (
			array (
				'key' => 'field_53c6ae8f2ccc1',
				'label' => 'Author',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53c6ae9b2ccc2',
				'label' => 'Author Name',
				'name' => 'author_name',
				'type' => 'text',
				'instructions' => 'Add author name.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53c6aeaa2ccc3',
				'label' => 'Author Position',
				'name' => 'author_position',
				'type' => 'text',
				'instructions' => 'Add author position or proffesion.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53c6acc0701ff',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53c6acfb634f8',
				'label' => 'Slider',
				'name' => 'slider',
				'type' => 'repeater',
				'instructions' => 'Add slider images.',
				'sub_fields' => array (
					array (
						'key' => 'field_53c6ad239b386',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add image.',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-aboutMe.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_aboutmembers',
		'title' => 'AboutMembers',
		'fields' => array (
			array (
				'key' => 'field_53c6dd38b7d1b',
				'label' => 'Authors',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53c6dd46b7d1c',
				'label' => 'Author',
				'name' => 'author',
				'type' => 'repeater',
				'instructions' => 'Add authors information.',
				'sub_fields' => array (
					array (
						'key' => 'field_53c6deaedbc3c',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add image for author',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array (
						'key' => 'field_53c6dd7ab7d1d',
						'label' => 'Author Name',
						'name' => 'author_name',
						'type' => 'text',
						'instructions' => 'Add author name.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53c6dd8eb7d1e',
						'label' => 'Author Position',
						'name' => 'author_position',
						'type' => 'text',
						'instructions' => 'Add author position.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53c6dda1b7d1f',
						'label' => 'Author Description',
						'name' => 'author_description',
						'type' => 'wysiwyg',
						'instructions' => 'Add author description.',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_53c6ddbdb7d20',
						'label' => 'Button Text',
						'name' => 'button_text',
						'type' => 'text',
						'instructions' => 'Add text button.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53c6dde2b7d21',
						'label' => 'Button Link',
						'name' => 'button_link',
						'type' => 'text',
						'instructions' => 'Add button link.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53c6de34b7d22',
						'label' => 'Social Networks',
						'name' => 'social_networks',
						'type' => 'repeater',
						'instructions' => 'Add social networks.',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53c6de47b7d23',
								'label' => 'Network',
								'name' => 'network',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'facebook' => 'facebook',
									'twitter' => 'twitter',
									'tumblr' => 'tumblr',
									'flickr' => 'flickr',
									'linkedin' => 'linkedin',
									'dribbble' => 'dribbble',
									'youtube' => 'youtube',
									'google-plus' => 'google+',
									'pinterest' => 'pinterest',
									'instagram' => 'instagram',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_53c6de66b7d24',
								'label' => 'Url',
								'name' => 'url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_aboutMembers.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_blog-circle',
		'title' => 'Blog Circle',
		'fields' => array (
			array (
				'key' => 'field_542da97473a7b',
				'label' => 'Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_542da97c73a7c',
				'label' => 'Post per page',
				'name' => 'post_per_page',
				'type' => 'number',
				'instructions' => 'Display Posts on page load and on load more. (Default is 3 posts).',
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_blogCircle.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_blog-masonry',
		'title' => 'Blog Masonry',
		'fields' => array (
			array (
				'key' => 'field_5424a44e4062b',
				'label' => 'Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_542da9103422c',
				'label' => 'Post per page',
				'name' => 'post_per_page',
				'type' => 'number',
				'instructions' => 'Display Posts on page load and on load more. (Default is 3 posts).',
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5424a45a4062c',
				'label' => 'Sidebar Off',
				'name' => 'sidebar_off',
				'type' => 'true_false',
				'instructions' => 'If checked disables sidebar.',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_blogMasonry.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_branding',
		'title' => 'Branding',
		'fields' => array (
			array (
				'key' => 'field_541b222ed6a39',
				'label' => 'Background',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_541b2244d6a3a',
				'label' => 'Background Color',
				'name' => 'background_color',
				'type' => 'color_picker',
				'instructions' => 'Choose website background color.',
				'default_value' => '',
			),
			array (
				'key' => 'field_542490a902afe',
				'label' => 'Overlay Color',
				'name' => 'overlay_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a color for overlays.',
				'default_value' => '',
			),
			array (
				'key' => 'field_541b2264d6a3b',
				'label' => 'Overlay Opacity',
				'name' => 'overlay_opacity',
				'type' => 'number',
				'instructions' => 'Choose a number between 0 and 10.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_541b228687dcd',
				'label' => 'Skin',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_541b22af87dce',
				'label' => 'Skin',
				'name' => 'skin',
				'type' => 'radio',
				'instructions' => 'Choose between light and dark skin.',
				'choices' => array (
					'main' => 'Light',
					'dark' => 'Dark',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_541b22e4e9f49',
				'label' => 'Brand Color',
				'name' => 'brand_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a color which represent you or your company.',
				'default_value' => '',
			),
			array (
				'key' => 'field_5424912c8eb2b',
				'label' => 'Brand Color Opacity',
				'name' => 'brand_color_opacity',
				'type' => 'number',
				'instructions' => 'Choose a number between 0 and 10.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_541b22f8e9f4a',
				'label' => 'Font',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_541b2301e9f4b',
				'label' => 'Web Site Font',
				'name' => 'web_site_font',
				'type' => 'googlefonts',
				'instructions' => 'Choose a Google font for your web.',
			),
			array (
				'key' => 'field_5424906e02afc',
				'label' => 'Headings Color',
				'name' => 'headings_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a color for headings.',
				'default_value' => '',
			),
			array (
				'key' => 'field_5424909202afd',
				'label' => 'Paragraphs Color',
				'name' => 'paragraphs_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a color for paragraphs.',
				'default_value' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-branding',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_contact',
		'title' => 'Contact',
		'fields' => array (
			array (
				'key' => 'field_53fe0828827db',
				'label' => 'Contact Form',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53fe086b827dc',
				'label' => 'Contact Form Title',
				'name' => 'contact_form_title',
				'type' => 'text',
				'instructions' => 'Add a title for contact form.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53fe0882827dd',
				'label' => 'Name Field',
				'name' => 'name_field',
				'type' => 'text',
				'instructions' => 'Add text to display in name field.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53fe08a3827de',
				'label' => 'Email Field',
				'name' => 'email_field',
				'type' => 'text',
				'instructions' => 'Add text to display in email field.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53fe08bd827df',
				'label' => 'Website',
				'name' => 'website',
				'type' => 'text',
				'instructions' => 'Add text for website field.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53fe08d8827e0',
				'label' => 'Message Field',
				'name' => 'message_field',
				'type' => 'textarea',
				'instructions' => 'Add text to display in message field.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_53fe09015fc44',
				'label' => 'Button Text',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => 'Add button text.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57f65c6868881',
				'label' => 'Email receiver',
				'name' => 'email_receiver',
				'type' => 'text',
				'instructions' => 'Add email to receive emails from contact form.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57f6602f83e94',
				'label' => 'Success Message',
				'name' => 'success_message',
				'type' => 'text',
				'instructions' => 'Add email success message.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57f6606683e95',
				'label' => 'Failed Message',
				'name' => 'failed_message',
				'type' => 'text',
				'instructions' => 'Add email fail send message.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53fe1e7d080af',
				'label' => 'Map Info',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53fe21800e2de',
				'label' => 'Map Title',
				'name' => 'map_title',
				'type' => 'text',
				'instructions' => 'Add map title.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53fe2318ad66a',
				'label' => 'Map Zoom',
				'name' => 'map_zoom',
				'type' => 'number',
				'instructions' => 'Add the level how deep the map should go.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53fe1e91080b0',
				'label' => 'Map',
				'name' => 'map',
				'type' => 'googlemap',
				'instructions' => 'Choose your location.',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_contact1.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_contact2.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_contact-details',
		'title' => 'Contact Details',
		'fields' => array (
			array (
				'key' => 'field_5405a525ef429',
				'label' => 'Details Name',
				'name' => 'details_name',
				'type' => 'text',
				'instructions' => 'Add details section title.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_540582d92ab2d',
				'label' => 'Details',
				'name' => 'details',
				'type' => 'repeater',
				'instructions' => 'Add contact details.',
				'sub_fields' => array (
					array (
						'key' => 'field_540583192ab2e',
						'label' => 'Details Title',
						'name' => 'details_title',
						'type' => 'text',
						'instructions' => 'Add details title',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5405832b2ab2f',
						'label' => 'Details Icon',
						'name' => 'details_icon',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'none' => 'none',
							'fa-glass' => '',
							'fa-music' => '',
							'fa-search' => '',
							'fa-envelope-o' => '',
							'fa-heart' => '',
							'fa-star' => '',
							'fa-star-o' => '',
							'fa-user' => '',
							'fa-film' => '',
							'fa-th-large' => '',
							'fa-th' => '',
							'fa-th-list' => '',
							'fa-check' => '',
							'fa-times' => '',
							'fa-search-plus' => '',
							'fa-search-minus' => '',
							'fa-power-off' => '',
							'fa-signal' => '',
							'fa-cog' => '',
							'fa-trash-o' => '',
							'fa-home' => '',
							'fa-file-o' => '',
							'fa-clock-o' => '',
							'fa-road' => '',
							'fa-download' => '',
							'fa-arrow-circle-o-down' => '',
							'fa-arrow-circle-o-up' => '',
							'fa-inbox' => '',
							'fa-play-circle-o' => '',
							'fa-repeat' => '',
							'fa-refresh' => '',
							'fa-list-alt' => '',
							'fa-lock' => '',
							'fa-flag' => '',
							'fa-headphones' => '',
							'fa-volume-off' => '',
							'fa-volume-down' => '',
							'fa-volume-up' => '',
							'fa-qrcode' => '',
							'fa-barcode' => '',
							'fa-tag' => '',
							'fa-tags' => '',
							'fa-book' => '',
							'fa-bookmark' => '',
							'fa-print' => '',
							'fa-camera' => '',
							'fa-font' => '',
							'fa-bold' => '',
							'fa-italic' => '',
							'fa-text-height' => '',
							'fa-text-width' => '',
							'fa-align-left' => '',
							'fa-align-center' => '',
							'fa-align-right' => '',
							'fa-align-justify' => '',
							'fa-list' => '',
							'fa-outdent' => '',
							'fa-indent' => '',
							'fa-video-camera' => '',
							'fa-picture-o' => '',
							'fa-pencil' => '',
							'fa-map-marker' => '',
							'fa-adjust' => '',
							'fa-tint' => '',
							'fa-pencil-square-o' => '',
							'fa-share-square-o' => '',
							'fa-check-square-o' => '',
							'fa-arrows' => '',
							'fa-step-backward' => '',
							'fa-fast-backward' => '',
							'fa-backward' => '',
							'fa-play' => '',
							'fa-pause' => '',
							'fa-stop' => '',
							'fa-forward' => '',
							'fa-fast-forward' => '',
							'fa-step-forward' => '',
							'fa-eject' => '',
							'fa-chevron-left' => '',
							'fa-chevron-right' => '',
							'fa-plus-circle' => '',
							'fa-minus-circle' => '',
							'fa-times-circle' => '',
							'fa-check-circle' => '',
							'fa-question-circle' => '',
							'fa-info-circle' => '',
							'fa-crosshairs' => '',
							'fa-times-circle-o' => '',
							'fa-check-circle-o' => '',
							'fa-ban' => '',
							'fa-arrow-left' => '',
							'fa-arrow-right' => '',
							'fa-arrow-up' => '',
							'fa-arrow-down' => '',
							'fa-share' => '',
							'fa-expand' => '',
							'fa-compress' => '',
							'fa-plus' => '',
							'fa-minus' => '',
							'fa-asterisk' => '',
							'fa-exclamation-circle' => '',
							'fa-gift' => '',
							'fa-leaf' => '',
							'fa-fire' => '',
							'fa-eye' => '',
							'fa-eye-slash' => '',
							'fa-exclamation-triangle' => '',
							'fa-plane' => '',
							'fa-calendar' => '',
							'fa-random' => '',
							'fa-comment' => '',
							'fa-magnet' => '',
							'fa-chevron-up' => '',
							'fa-chevron-down' => '',
							'fa-retweet' => '',
							'fa-shopping-cart' => '',
							'fa-folder' => '',
							'fa-folder-open' => '',
							'fa-arrows-v' => '',
							'fa-arrows-h' => '',
							'fa-bar-chart-o' => '',
							'fa-twitter-square' => '',
							'fa-facebook-square' => '',
							'fa-camera-retro' => '',
							'fa-key' => '',
							'fa-cogs' => '',
							'fa-comments' => '',
							'fa-thumbs-o-up' => '',
							'fa-thumbs-o-down' => '',
							'fa-star-half' => '',
							'fa-heart-o' => '',
							'fa-sign-out' => '',
							'fa-linkedin-square' => '',
							'fa-thumb-tack' => '',
							'fa-external-link' => '',
							'fa-sign-in' => '',
							'fa-trophy' => '',
							'fa-github-square' => '',
							'fa-upload' => '',
							'fa-lemon-o' => '',
							'fa-phone' => '',
							'fa-square-o' => '',
							'fa-bookmark-o' => '',
							'fa-phone-square' => '',
							'fa-twitter' => '',
							'fa-facebook' => '',
							'fa-github' => '',
							'fa-unlock' => '',
							'fa-credit-card' => '',
							'fa-rss' => '',
							'fa-hdd-o' => '',
							'fa-bullhorn' => '',
							'fa-bell' => '',
							'fa-certificate' => '',
							'fa-hand-o-right' => '',
							'fa-hand-o-left' => '',
							'fa-hand-o-up' => '',
							'fa-hand-o-down' => '',
							'fa-arrow-circle-left' => '',
							'fa-arrow-circle-right' => '',
							'fa-arrow-circle-up' => '',
							'fa-arrow-circle-down' => '',
							'fa-globe' => '',
							'fa-wrench' => '',
							'fa-tasks' => '',
							'fa-filter' => '',
							'fa-briefcase' => '',
							'fa-arrows-alt' => '',
							'fa-users' => '',
							'fa-link' => '',
							'fa-cloud' => '',
							'fa-flask' => '',
							'fa-scissors' => '',
							'fa-files-o' => '',
							'fa-paperclip' => '',
							'fa-floppy-o' => '',
							'fa-square' => '',
							'fa-bars' => '',
							'fa-list-ul' => '',
							'fa-list-ol' => '',
							'fa-strikethrough' => '',
							'fa-underline' => '',
							'fa-table' => '',
							'fa-magic' => '',
							'fa-truck' => '',
							'fa-pinterest' => '',
							'fa-pinterest-square' => '',
							'fa-google-plus-square' => '',
							'fa-google-plus' => '',
							'fa-money' => '',
							'fa-caret-down' => '',
							'fa-caret-up' => '',
							'fa-caret-left' => '',
							'fa-caret-right' => '',
							'fa-columns' => '',
							'fa-sort' => '',
							'fa-sort-asc' => '',
							'fa-sort-desc' => '',
							'fa-envelope' => '',
							'fa-linkedin' => '',
							'fa-undo' => '',
							'fa-gavel' => '',
							'fa-tachometer' => '',
							'fa-comment-o' => '',
							'fa-comments-o' => '',
							'fa-bolt' => '',
							'fa-sitemap' => '',
							'fa-umbrella' => '',
							'fa-clipboard' => '',
							'fa-lightbulb-o' => '',
							'fa-exchange' => '',
							'fa-cloud-download' => '',
							'fa-cloud-upload' => '',
							'fa-user-md' => '',
							'fa-stethoscope' => '',
							'fa-suitcase' => '',
							'fa-bell-o' => '',
							'fa-coffee' => '',
							'fa-cutlery' => '',
							'fa-file-text-o' => '',
							'fa-building-o' => '',
							'fa-hospital-o' => '',
							'fa-ambulance' => '',
							'fa-medkit' => '',
							'fa-fighter-jet' => '',
							'fa-beer' => '',
							'fa-h-square' => '',
							'fa-plus-square' => '',
							'fa-angle-double-left' => '',
							'fa-angle-double-right' => '',
							'fa-angle-double-up' => '',
							'fa-angle-double-down' => '',
							'fa-angle-left' => '',
							'fa-angle-right' => '',
							'fa-angle-up' => '',
							'fa-angle-down' => '',
							'fa-desktop' => '',
							'fa-laptop' => '',
							'fa-tablet' => '',
							'fa-mobile' => '',
							'fa-circle-o' => '',
							'fa-quote-left' => '',
							'fa-quote-right' => '',
							'fa-spinner' => '',
							'fa-circle' => '',
							'fa-reply' => '',
							'fa-github-alt' => '',
							'fa-folder-o' => '',
							'fa-folder-open-o' => '',
							'fa-smile-o' => '',
							'fa-frown-o' => '',
							'fa-meh-o' => '',
							'fa-gamepad' => '',
							'fa-keyboard-o' => '',
							'fa-flag-o' => '',
							'fa-flag-checkered' => '',
							'fa-terminal' => '',
							'fa-code' => '',
							'fa-reply-all' => '',
							'fa-mail-reply-all' => '',
							'fa-star-half-o' => '',
							'fa-location-arrow' => '',
							'fa-crop' => '',
							'fa-code-fork' => '',
							'fa-chain-broken' => '',
							'fa-question' => '',
							'fa-info' => '',
							'fa-exclamation' => '',
							'fa-superscript' => '',
							'fa-subscript' => '',
							'fa-eraser' => '',
							'fa-puzzle-piece' => '',
							'fa-microphone' => '',
							'fa-microphone-slash' => '',
							'fa-shield' => '',
							'fa-calendar-o' => '',
							'fa-fire-extinguisher' => '',
							'fa-rocket' => '',
							'fa-maxcdn' => '',
							'fa-chevron-circle-left' => '',
							'fa-chevron-circle-right' => '',
							'fa-chevron-circle-up' => '',
							'fa-chevron-circle-down' => '',
							'fa-html5' => '',
							'fa-css3' => '',
							'fa-anchor' => '',
							'fa-unlock-alt' => '',
							'fa-bullseye' => '',
							'fa-ellipsis-h' => '',
							'fa-ellipsis-v' => '',
							'fa-rss-square' => '',
							'fa-play-circle' => '',
							'fa-ticket' => '',
							'fa-minus-square' => '',
							'fa-minus-square-o' => '',
							'fa-level-up' => '',
							'fa-level-down' => '',
							'fa-check-square' => '',
							'fa-pencil-square' => '',
							'fa-external-link-square' => '',
							'fa-share-square' => '',
							'fa-compass' => '',
							'fa-caret-square-o-down' => '',
							'fa-caret-square-o-up' => '',
							'fa-caret-square-o-right' => '',
							'fa-eur' => '',
							'fa-gbp' => '',
							'fa-usd' => '',
							'fa-inr' => '',
							'fa-jpy' => '',
							'fa-rub' => '',
							'fa-krw' => '',
							'fa-btc' => '',
							'fa-file' => '',
							'fa-file-text' => '',
							'fa-sort-alpha-asc' => '',
							'fa-sort-alpha-desc' => '',
							'fa-sort-amount-asc' => '',
							'fa-sort-amount-desc' => '',
							'fa-sort-numeric-asc' => '',
							'fa-sort-numeric-desc' => '',
							'fa-thumbs-up' => '',
							'fa-thumbs-down' => '',
							'fa-youtube-square' => '',
							'fa-youtube' => '',
							'fa-xing' => '',
							'fa-xing-square' => '',
							'fa-youtube-play' => '',
							'fa-dropbox' => '',
							'fa-stack-overflow' => '',
							'fa-instagram' => '',
							'fa-flickr' => '',
							'fa-adn' => '',
							'fa-bitbucket' => '',
							'fa-bitbucket-square' => '',
							'fa-tumblr' => '',
							'fa-tumblr-square' => '',
							'fa-long-arrow-down' => '',
							'fa-long-arrow-up' => '',
							'fa-long-arrow-left' => '',
							'fa-long-arrow-right' => '',
							'fa-apple' => '',
							'fa-windows' => '',
							'fa-android' => '',
							'fa-linux' => '',
							'fa-dribbble' => '',
							'fa-skype' => '',
							'fa-foursquare' => '',
							'fa-trello' => '',
							'fa-female' => '',
							'fa-male' => '',
							'fa-gittip' => '',
							'fa-sun-o' => '',
							'fa-moon-o' => '',
							'fa-archive' => '',
							'fa-bug' => '',
							'fa-vk' => '',
							'fa-weibo' => '',
							'fa-renren' => '',
							'fa-pagelines' => '',
							'fa-stack-exchange' => '',
							'fa-arrow-circle-o-right' => '',
							'fa-arrow-circle-o-left' => '',
							'fa-caret-square-o-left' => '',
							'fa-dot-circle-o' => '',
							'fa-wheelchair' => '',
							'fa-vimeo-square' => '',
							'fa-try' => '',
							'fa-plus-square-o' => '',
						),
						'default_value' => 'Choose a font awesome',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_540583412ab30',
						'label' => 'Details Content',
						'name' => 'details_content',
						'type' => 'wysiwyg',
						'instructions' => 'Add details content',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_contact2.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_footer',
		'title' => 'Footer',
		'fields' => array (
			array (
				'key' => 'field_542af8cc8a843',
				'label' => 'Disable Footer',
				'name' => 'disable_footer',
				'type' => 'true_false',
				'instructions' => 'If checked disables footer.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_541a89caebdbb',
				'label' => 'Left Content',
				'name' => 'left_content',
				'type' => 'wysiwyg',
				'instructions' => 'Add your left footer content.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_541a8a24ebdbc',
				'label' => 'Right Content',
				'name' => 'right_content',
				'type' => 'wysiwyg',
				'instructions' => 'Add your right footer content.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-footer',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_fullscreen-slider',
		'title' => 'Fullscreen Slider',
		'fields' => array (
			array (
				'key' => 'field_5412b3ec4a304',
				'label' => 'Slider Animation',
				'name' => 'slider_animation',
				'type' => 'select',
				'instructions' => 'Choose Slider Animation.',
				'choices' => array (
					'fxFade' => 'Fade',
					'fxSoftScale' => 'SoftScale',
					'fxPressAway' => 'PressAway',
					'fxSideSwing' => 'SideSwing',
					'fxFortuneWheel' => 'FortuneWheel',
					'fxSwipe' => 'Swipe',
					'fxSwipeHorizontal' => 'SwipeHorizontal',
					'fxPushReveal' => 'PushReveal',
					'fxSnapIn' => 'SnapIn',
					'fxLetMeIn' => 'LetMeIn',
					'fxStickIt' => 'StickIt',
					'fxArchiveMe' => 'ArchiveMe',
					'fxVGrowth' => 'VGrowth',
					'fxSlideBehind' => 'SlideBehind',
					'fxSoftPulse' => 'SoftPulse',
					'fxEarthquake' => 'Earthquake',
					'fxCliffDiving' => 'CliffDiving',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5412d8b02c93a',
				'label' => 'Autoplay Duration',
				'name' => 'autoplay_duration',
				'type' => 'number',
				'instructions' => 'Select slider autoplay duration.',
				'default_value' => 0,
				'placeholder' => 0,
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53cfa6a62f1b5',
				'label' => 'Gallery',
				'name' => 'gallery',
				'type' => 'repeater',
				'instructions' => 'Add gallery images.',
				'sub_fields' => array (
					array (
						'key' => 'field_53cfa6d82f1b6',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add Image.',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array (
						'key' => 'field_53cfa7142f1b7',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => 'Add text to display on image.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5412b396b7cd7',
						'label' => 'Text Animation',
						'name' => 'text_animation',
						'type' => 'select',
						'instructions' => 'Choose text animation.',
						'column_width' => '',
						'choices' => array (
							'bounce' => 'bounce',
							'flash' => 'flash',
							'pulse' => 'pulse',
							'rubberBand' => 'rubberBand',
							'shake' => 'shake',
							'swing' => 'swing',
							'tada' => 'tada',
							'wobble' => 'wobble',
							'bounceIn' => 'bounceIn',
							'bounceInDown' => 'bounceInDown',
							'bounceInLeft' => 'bounceInLeft',
							'bounceInRight' => 'bounceInRight',
							'bounceInUp' => 'bounceInUp',
							'fadeIn' => 'fadeIn',
							'fadeInDown' => 'fadeInDown',
							'fadeInDownBig' => 'fadeInDownBig',
							'fadeInLeft' => 'fadeInLeft',
							'fadeInLeftBig' => 'fadeInLeftBig',
							'fadeInRight' => 'fadeInRight',
							'fadeInRightBig' => 'fadeInRightBig',
							'fadeInUp' => 'fadeInUp',
							'fadeInUpBig' => 'fadeInUpBig',
							'flip' => 'flip',
							'flipInX' => 'flipInX',
							'flipInY' => 'flipInY',
							'lightSpeedIn' => 'lightSpeedIn',
							'rotateIn' => 'rotateIn',
							'rotateInDownLeft' => 'rotateInDownLeft',
							'rotateInDownRight' => 'rotateInDownRight',
							'rotateInUpLeft' => 'rotateInUpLeft',
							'rotateInUpRight' => 'rotateInUpRight',
							'rollIn' => 'rollIn',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53cfa75f5d96d',
						'label' => 'Link Text',
						'name' => 'link_text',
						'type' => 'text',
						'instructions' => 'Add link text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53cfa7715d96e',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => 'Add link address.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5412b3cab7cd8',
						'label' => 'Link Animation',
						'name' => 'link_animation',
						'type' => 'select',
						'instructions' => 'Choose link animation.',
						'column_width' => '',
						'choices' => array (
							'bounce' => 'bounce',
							'flash' => 'flash',
							'pulse' => 'pulse',
							'rubberBand' => 'rubberBand',
							'shake' => 'shake',
							'swing' => 'swing',
							'tada' => 'tada',
							'wobble' => 'wobble',
							'bounceIn' => 'bounceIn',
							'bounceInDown' => 'bounceInDown',
							'bounceInLeft' => 'bounceInLeft',
							'bounceInRight' => 'bounceInRight',
							'bounceInUp' => 'bounceInUp',
							'fadeIn' => 'fadeIn',
							'fadeInDown' => 'fadeInDown',
							'fadeInDownBig' => 'fadeInDownBig',
							'fadeInLeft' => 'fadeInLeft',
							'fadeInLeftBig' => 'fadeInLeftBig',
							'fadeInRight' => 'fadeInRight',
							'fadeInRightBig' => 'fadeInRightBig',
							'fadeInUp' => 'fadeInUp',
							'fadeInUpBig' => 'fadeInUpBig',
							'flip' => 'flip',
							'flipInX' => 'flipInX',
							'flipInY' => 'flipInY',
							'lightSpeedIn' => 'lightSpeedIn',
							'rotateIn' => 'rotateIn',
							'rotateInDownLeft' => 'rotateInDownLeft',
							'rotateInDownRight' => 'rotateInDownRight',
							'rotateInUpLeft' => 'rotateInUpLeft',
							'rotateInUpRight' => 'rotateInUpRight',
							'rollIn' => 'rollIn',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_53cfa78a5d96f',
						'label' => 'Description',
						'name' => 'copyright',
						'type' => 'text',
						'instructions' => 'Describe your image.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_542016802d125',
						'label' => 'Crop',
						'name' => 'crop',
						'type' => 'true_false',
						'instructions' => 'Check to crop the image',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_fullscreenSlider.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_gallery-all-options',
		'title' => 'Gallery All Options',
		'fields' => array (
			array (
				'key' => 'field_57f66638b7710',
				'label' => 'Pages',
				'name' => 'pages',
				'type' => 'relationship',
				'return_format' => 'id',
				'post_type' => array (
					0 => 'page',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_type',
					2 => 'post_title',
				),
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_galleryAll.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_gallery-circle',
		'title' => 'Gallery Circle',
		'fields' => array (
			array (
				'key' => 'field_542d9591b9c84',
				'label' => 'Slider Animation',
				'name' => 'slider_animation',
				'type' => 'select',
				'instructions' => 'Choose Slider Animation.',
				'choices' => array (
					'fxFade' => 'Fade',
					'fxSwipe' => 'Swipe',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_540704a0135c9',
				'label' => 'Gallery',
				'name' => 'gallery',
				'type' => 'repeater',
				'instructions' => 'Add gallery images.',
				'sub_fields' => array (
					array (
						'key' => 'field_540704de135ca',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add image.',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array (
						'key' => 'field_540704f9135cb',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => 'Add text to display on image.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_542d927bc24a4',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'instructions' => 'Add image description.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_54070507135cc',
						'label' => 'Categories',
						'name' => 'categories',
						'type' => 'taxonomy',
						'column_width' => '',
						'taxonomy' => 'gallery',
						'field_type' => 'checkbox',
						'allow_null' => 0,
						'load_save_terms' => 0,
						'return_format' => 'object',
						'multiple' => 0,
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_threeCirlces.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_gallery-posts',
		'title' => 'Gallery Posts',
		'fields' => array (
			array (
				'key' => 'field_53ca69f902c8c',
				'label' => 'Gallery Images',
				'name' => 'gallery_images',
				'type' => 'repeater',
				'instructions' => 'Add images.',
				'sub_fields' => array (
					array (
						'key' => 'field_53ca6a0a02c8d',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'gallery',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_gallery-small',
		'title' => 'Gallery Small',
		'fields' => array (
			array (
				'key' => 'field_542b111f4271a',
				'label' => 'Slider Animation',
				'name' => 'slider_animation',
				'type' => 'select',
				'instructions' => 'Choose Slider Animation.',
				'choices' => array (
					'fxFade' => 'Fade',
					'fxSwipe' => 'Swipe',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53cfb596ad6a9',
				'label' => 'Gallery',
				'name' => 'gallery',
				'type' => 'repeater',
				'instructions' => 'Add gallery images.',
				'sub_fields' => array (
					array (
						'key' => 'field_543a9ac9213b9',
						'label' => 'Type',
						'name' => 'type',
						'type' => 'radio',
						'instructions' => 'Choose between image and video.',
						'column_width' => '',
						'choices' => array (
							'image' => 'Image',
							'video' => 'Video',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'image',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_53cfb5a8ad6aa',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add image.',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array (
						'key' => 'field_543a9b2c213ba',
						'label' => 'Video Url',
						'name' => 'video_url',
						'type' => 'text',
						'instructions' => 'Add video url here (youtube and vimeo are supported).',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_543aa4b8a4b3a',
						'label' => 'Video Thumb',
						'name' => 'video_thumb',
						'type' => 'image',
						'instructions' => 'Add video thumbnail.',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_542c4b0053c41',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'instructions' => 'Add image description.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_542020815e11e',
						'label' => 'Crop',
						'name' => 'crop',
						'type' => 'true_false',
						'instructions' => 'Check to crop the image',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_smallSlider.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_panorama.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_panoramaAlt.php',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_header',
		'title' => 'Header',
		'fields' => array (
			array (
				'key' => 'field_540ef9776c303',
				'label' => 'FavIcon and Logo Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_540ef9866c304',
				'label' => 'Fav Icon',
				'name' => 'fav_icon',
				'type' => 'image',
				'instructions' => 'Add site fav icon.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_540ef9a06c305',
				'label' => 'Logo Type',
				'name' => 'logo_type',
				'type' => 'radio',
				'instructions' => 'Choose logo type.',
				'choices' => array (
					'image' => 'Image',
					'text' => 'Text',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_540ef9c0b7c43',
				'label' => 'Logo',
				'name' => 'logo',
				'type' => 'image',
				'instructions' => 'Choose logo image.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_540ef9a06c305',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_540ef9e4df39f',
				'label' => 'Logo Width',
				'name' => 'logo_width',
				'type' => 'number',
				'instructions' => 'Set the width of logo.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_540ef9a06c305',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_540ef9fedf3a0',
				'label' => 'Logo Height',
				'name' => 'logo_height',
				'type' => 'number',
				'instructions' => 'Set the height of logo.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_540ef9a06c305',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_540efa170deb4',
				'label' => 'Text Logo',
				'name' => 'text_logo',
				'type' => 'text',
				'instructions' => 'Add Text as logo. Note: this text only shows if you do not insert a logo image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_540ef9a06c305',
							'operator' => '==',
							'value' => 'text',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_540efa2e0deb5',
				'label' => 'Text Logo Color',
				'name' => 'text_logo_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a color to the text logo',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_540ef9a06c305',
							'operator' => '==',
							'value' => 'text',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
			),
			array (
				'key' => 'field_540efa490deb6',
				'label' => 'Text Logo Font',
				'name' => 'text_logo_font',
				'type' => 'googlefonts',
				'instructions' => 'Choose the text logo font (Google fonts)',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_540ef9a06c305',
							'operator' => '==',
							'value' => 'text',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_540efa5e0deb7',
				'label' => 'Text Font Size',
				'name' => 'text_font_size',
				'type' => 'number',
				'instructions' => 'Choose the size of the logo font.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_540ef9a06c305',
							'operator' => '==',
							'value' => 'text',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_540efa786d88c',
				'label' => 'Social Icons',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_540efa8b6d88d',
				'label' => 'Social Networks',
				'name' => 'social_networks',
				'type' => 'repeater',
				'instructions' => 'Add your social media links.',
				'sub_fields' => array (
					array (
						'key' => 'field_540efa9e6d88e',
						'label' => 'Network',
						'name' => 'network',
						'type' => 'select',
						'instructions' => 'Choose social networks.',
						'column_width' => '',
						'choices' => array (
							'fa-twitter' => 'Twitter',
							'fa-facebook' => 'Facebook',
							'fa-pinterest' => 'Pinterest',
							'fa-tumblr' => 'Tumblr',
							'fa-weibo' => 'Weibo',
							'fa-youtube' => 'Youtube',
							'fa-linkedin' => 'linkedIn',
							'fa-google-plus' => 'google+',
							'fa-flickr' => 'flickr',
							'fa-dribbble' => 'dribbble',
							'fa-instagram' => 'instagram',
							'fa-vimeo-square' => 'Vimeo',
							'fa-skype' => 'Skype',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_540efac46d88f',
						'label' => 'Url',
						'name' => 'url',
						'type' => 'text',
						'instructions' => 'Add url of your social network.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-header',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_home-shop',
		'title' => 'Home Shop',
		'fields' => array (
			array (
				'key' => 'field_57f64cc886355',
				'label' => 'Background Image',
				'name' => 'background_image',
				'type' => 'image',
				'instructions' => 'Add page backround.',
				'save_format' => 'url',
				'preview_size' => 'large',
				'library' => 'all',
			),
			array (
				'key' => 'field_57f64cc886e6a',
				'label' => 'Slider Animation',
				'name' => 'slider_animation',
				'type' => 'select',
				'instructions' => 'Choose Slider Animation.',
				'choices' => array (
					'fxFade' => 'Fade',
					'fxSwipe' => 'Swipe',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_57f64cc885313',
				'label' => 'Products',
				'name' => 'products',
				'type' => 'relationship',
				'instructions' => 'Choose products to show on page.',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'product',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_type',
					2 => 'post_title',
				),
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-homeShop.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_horizontal',
		'title' => 'Horizontal',
		'fields' => array (
			array (
				'key' => 'field_53dfb07105de9',
				'label' => 'Background Image',
				'name' => 'background_image',
				'type' => 'image',
				'instructions' => 'Add page backround.',
				'save_format' => 'url',
				'preview_size' => 'large',
				'library' => 'all',
			),
			array (
				'key' => 'field_542d954f84334',
				'label' => 'Slider Animation',
				'name' => 'slider_animation',
				'type' => 'select',
				'instructions' => 'Choose Slider Animation.',
				'choices' => array (
					'fxFade' => 'Fade',
					'fxSwipe' => 'Swipe',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53ce4e231711a',
				'label' => 'Gallery',
				'name' => 'gallery',
				'type' => 'repeater',
				'instructions' => 'Add gallery images.',
				'sub_fields' => array (
					array (
						'key' => 'field_543c1b1262841',
						'label' => 'Type',
						'name' => 'type',
						'type' => 'radio',
						'instructions' => 'Choose between image and video.',
						'column_width' => '',
						'choices' => array (
							'image' => 'Image',
							'video' => 'Video',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'image',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_53ce4e4d1711b',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array (
						'key' => 'field_543c1b4362842',
						'label' => 'Video Url',
						'name' => 'video_url',
						'type' => 'text',
						'instructions' => 'Add video url here (youtube and vimeo are supported).',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_543c1b7a62843',
						'label' => 'Video Thumb',
						'name' => 'video_thumb',
						'type' => 'image',
						'instructions' => 'Add video thumbnail.',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_53ce4e591711c',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => 'Add text to display on image.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_542d924a55b18',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'instructions' => 'Add image description.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_53ce4e6c1711d',
						'label' => 'Categories',
						'name' => 'categories',
						'type' => 'taxonomy',
						'column_width' => '',
						'taxonomy' => 'gallery',
						'field_type' => 'checkbox',
						'allow_null' => 0,
						'load_save_terms' => 0,
						'return_format' => 'object',
						'multiple' => 0,
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_Horizontal.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_HorizontalSmall.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_main',
		'title' => 'Main',
		'fields' => array (
			array (
				'key' => 'field_54084fae9b8d0',
				'label' => 'Social Shares',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54084ff09b8d1',
				'label' => 'Disable Blog Social Shares',
				'name' => 'disable_blog_social_shares',
				'type' => 'true_false',
				'instructions' => 'If checked disables shares for blog posts.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_54084ffe9b8d2',
				'label' => 'Disable Project Social Shares',
				'name' => 'disable_project_social_shares',
				'type' => 'true_false',
				'instructions' => 'If checked disables project posts shares.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5408500e9b8d3',
				'label' => 'Share Posts',
				'name' => 'share_posts',
				'type' => 'checkbox',
				'instructions' => 'Share posts.',
				'choices' => array (
					'facebook' => 'Facebook',
					'twitter' => 'Twitter',
					'google' => 'Google+',
					'linkedin' => 'LinkedIn',
					'pinit' => 'Pinterest',
				),
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_540ef85b656da',
				'label' => 'Custom Css & Js',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_540ef867656db',
				'label' => 'Custom Css',
				'name' => 'custom_css',
				'type' => 'textarea',
				'instructions' => 'Add your custom css.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_540ef874656dc',
				'label' => 'Custom JS',
				'name' => 'custom_js',
				'type' => 'textarea',
				'instructions' => 'Add your custom css.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_57f50c274b852',
				'label' => 'Google Map',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57f50bfd4b851',
				'label' => 'Google Maps API key',
				'name' => 'google_maps_api_key',
				'type' => 'text',
				'instructions' => 'Check <a href="http://throne.stonedthemes.com/documentation/#5" target="_blank">documentation</a> on how to get a google api key.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-main',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_mix-page',
		'title' => 'Mix Page',
		'fields' => array (
			array (
				'key' => 'field_542e3a0325822',
				'label' => 'Autoplay Duration',
				'name' => 'autoplay_duration',
				'type' => 'number',
				'instructions' => 'Select slider autoplay duration.',
				'default_value' => 0,
				'placeholder' => 0,
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_542e3a2425823',
				'label' => 'Gallery',
				'name' => 'gallery',
				'type' => 'repeater',
				'instructions' => 'Add gallery images.',
				'sub_fields' => array (
					array (
						'key' => 'field_542e3a3925824',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array (
						'key' => 'field_542e3a5425825',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => 'Add text to display on image.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_542e3a6d25826',
						'label' => 'Link Text',
						'name' => 'link_text',
						'type' => 'text',
						'instructions' => 'Add link text.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_542e3a8525827',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => 'Add link address.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_542e3aa125828',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'text',
						'instructions' => 'Describe your image.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_542e3ab825829',
						'label' => 'Crop',
						'name' => 'crop',
						'type' => 'true_false',
						'instructions' => 'Check to crop the image',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-mixPage.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_mosaicdisplay',
		'title' => 'MosaicDisplay',
		'fields' => array (
			array (
				'key' => 'field_5419917d12378',
				'label' => 'DisplayMode',
				'name' => 'displaymode',
				'type' => 'radio',
				'choices' => array (
					'horizontalRect' => 'BigSquare',
					'verticalRect' => 'VerticalRect',
					'square' => 'SmallSquare',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'project_post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-mosaic',
		'title' => 'Portfolio Mosaic',
		'fields' => array (
			array (
				'key' => 'field_5423261e65506',
				'label' => 'Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_542da01d768f8',
				'label' => 'Post per page',
				'name' => 'post_per_page',
				'type' => 'number',
				'instructions' => 'Display Posts on page load and on load more. (Default is 3 posts)',
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5423262865507',
				'label' => 'Layout',
				'name' => 'layout',
				'type' => 'radio',
				'instructions' => 'Choose page layout.',
				'choices' => array (
					'fullwidth' => 'FullWidth',
					'incontainer' => 'FixedGrid',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_portfolioMosaic.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-mosaic1',
		'title' => 'Portfolio Mosaic1',
		'fields' => array (
			array (
				'key' => 'field_542c34a31bd05',
				'label' => 'Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_542c34ae1bd06',
				'label' => 'Project Post',
				'name' => 'project_post',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_542c36b391304',
						'label' => 'Post',
						'name' => 'post',
						'type' => 'post_object',
						'instructions' => 'Choose post.',
						'column_width' => '',
						'post_type' => array (
							0 => 'project_post',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_542c36d791305',
						'label' => 'Display',
						'name' => 'display',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'bigSquare' => 'Big Square',
							'smallSquare' => 'Small Square',
							'verticalRect' => 'Vertical Rect',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => '',
						'layout' => 'vertical',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_portfolioMosaic1.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-options',
		'title' => 'Portfolio Options',
		'fields' => array (
			array (
				'key' => 'field_542321a2f40eb',
				'label' => 'Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_542da3e782b8c',
				'label' => 'Post per page',
				'name' => 'post_per_page',
				'type' => 'number',
				'instructions' => 'Display Posts on page load and on load more. (Default is 3 posts).',
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_542321b0f40ec',
				'label' => 'Layout',
				'name' => 'layout',
				'type' => 'radio',
				'instructions' => 'Choose page layout.',
				'choices' => array (
					'fullwidth' => 'FullWidth',
					'incontainer' => 'FixedGrid',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_54232207f40ed',
				'label' => 'Columns',
				'name' => 'columns',
				'type' => 'select',
				'instructions' => 'Choose between 2,3 or 4 columns.',
				'choices' => array (
					2 => '2 Columns',
					3 => '3 Columns',
					4 => '4 Columns',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_portfolioMasonry.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_portfolioSquare3.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_portfolioSquare4.php',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_projects',
		'title' => 'Projects',
		'fields' => array (
			array (
				'key' => 'field_53c82b043e501',
				'label' => 'Project Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5408549dd04f4',
				'label' => 'Slider Display',
				'name' => 'slider_display',
				'type' => 'radio',
				'instructions' => 'Choose how you want to display images.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'null',
							'operator' => '==',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'slider' => 'Slider',
					'mosaic' => 'Mosaic',
					'masonry' => 'Masonry',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53c82d2eeb8e5',
				'label' => 'Slider',
				'name' => 'slider',
				'type' => 'repeater',
				'instructions' => 'Add slider images.',
				'sub_fields' => array (
					array (
						'key' => 'field_53c82d4eeb8e6',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Add image.',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'project_post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_service-page',
		'title' => 'Service Page',
		'fields' => array (
			array (
				'key' => 'field_53d28b70536b1',
				'label' => 'Services',
				'name' => 'services',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'service_post',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_type',
					1 => 'post_title',
				),
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_services.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_services',
		'title' => 'Services',
		'fields' => array (
			array (
				'key' => 'field_53d11a22246ee',
				'label' => 'Type',
				'name' => 'type',
				'type' => 'radio',
				'instructions' => 'Choose service type.',
				'choices' => array (
					'font-awesome' => 'Font Awesome',
					'image' => 'Image',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53d11ac7c33f7',
				'label' => 'Font awesome',
				'name' => 'font_awesome',
				'type' => 'select',
				'instructions' => 'Choose the service icon.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53d11a22246ee',
							'operator' => '==',
							'value' => 'font-awesome',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'none' => 'none',
					'fa-glass' => '',
					'fa-music' => '',
					'fa-search' => '',
					'fa-envelope-o' => '',
					'fa-heart' => '',
					'fa-star' => '',
					'fa-star-o' => '',
					'fa-user' => '',
					'fa-film' => '',
					'fa-th-large' => '',
					'fa-th' => '',
					'fa-th-list' => '',
					'fa-check' => '',
					'fa-times' => '',
					'fa-search-plus' => '',
					'fa-search-minus' => '',
					'fa-power-off' => '',
					'fa-signal' => '',
					'fa-cog' => '',
					'fa-trash-o' => '',
					'fa-home' => '',
					'fa-file-o' => '',
					'fa-clock-o' => '',
					'fa-road' => '',
					'fa-download' => '',
					'fa-arrow-circle-o-down' => '',
					'fa-arrow-circle-o-up' => '',
					'fa-inbox' => '',
					'fa-play-circle-o' => '',
					'fa-repeat' => '',
					'fa-refresh' => '',
					'fa-list-alt' => '',
					'fa-lock' => '',
					'fa-flag' => '',
					'fa-headphones' => '',
					'fa-volume-off' => '',
					'fa-volume-down' => '',
					'fa-volume-up' => '',
					'fa-qrcode' => '',
					'fa-barcode' => '',
					'fa-tag' => '',
					'fa-tags' => '',
					'fa-book' => '',
					'fa-bookmark' => '',
					'fa-print' => '',
					'fa-camera' => '',
					'fa-font' => '',
					'fa-bold' => '',
					'fa-italic' => '',
					'fa-text-height' => '',
					'fa-text-width' => '',
					'fa-align-left' => '',
					'fa-align-center' => '',
					'fa-align-right' => '',
					'fa-align-justify' => '',
					'fa-list' => '',
					'fa-outdent' => '',
					'fa-indent' => '',
					'fa-video-camera' => '',
					'fa-picture-o' => '',
					'fa-pencil' => '',
					'fa-map-marker' => '',
					'fa-adjust' => '',
					'fa-tint' => '',
					'fa-pencil-square-o' => '',
					'fa-share-square-o' => '',
					'fa-check-square-o' => '',
					'fa-arrows' => '',
					'fa-step-backward' => '',
					'fa-fast-backward' => '',
					'fa-backward' => '',
					'fa-play' => '',
					'fa-pause' => '',
					'fa-stop' => '',
					'fa-forward' => '',
					'fa-fast-forward' => '',
					'fa-step-forward' => '',
					'fa-eject' => '',
					'fa-chevron-left' => '',
					'fa-chevron-right' => '',
					'fa-plus-circle' => '',
					'fa-minus-circle' => '',
					'fa-times-circle' => '',
					'fa-check-circle' => '',
					'fa-question-circle' => '',
					'fa-info-circle' => '',
					'fa-crosshairs' => '',
					'fa-times-circle-o' => '',
					'fa-check-circle-o' => '',
					'fa-ban' => '',
					'fa-arrow-left' => '',
					'fa-arrow-right' => '',
					'fa-arrow-up' => '',
					'fa-arrow-down' => '',
					'fa-share' => '',
					'fa-expand' => '',
					'fa-compress' => '',
					'fa-plus' => '',
					'fa-minus' => '',
					'fa-asterisk' => '',
					'fa-exclamation-circle' => '',
					'fa-gift' => '',
					'fa-leaf' => '',
					'fa-fire' => '',
					'fa-eye' => '',
					'fa-eye-slash' => '',
					'fa-exclamation-triangle' => '',
					'fa-plane' => '',
					'fa-calendar' => '',
					'fa-random' => '',
					'fa-comment' => '',
					'fa-magnet' => '',
					'fa-chevron-up' => '',
					'fa-chevron-down' => '',
					'fa-retweet' => '',
					'fa-shopping-cart' => '',
					'fa-folder' => '',
					'fa-folder-open' => '',
					'fa-arrows-v' => '',
					'fa-arrows-h' => '',
					'fa-bar-chart-o' => '',
					'fa-twitter-square' => '',
					'fa-facebook-square' => '',
					'fa-camera-retro' => '',
					'fa-key' => '',
					'fa-cogs' => '',
					'fa-comments' => '',
					'fa-thumbs-o-up' => '',
					'fa-thumbs-o-down' => '',
					'fa-star-half' => '',
					'fa-heart-o' => '',
					'fa-sign-out' => '',
					'fa-linkedin-square' => '',
					'fa-thumb-tack' => '',
					'fa-external-link' => '',
					'fa-sign-in' => '',
					'fa-trophy' => '',
					'fa-github-square' => '',
					'fa-upload' => '',
					'fa-lemon-o' => '',
					'fa-phone' => '',
					'fa-square-o' => '',
					'fa-bookmark-o' => '',
					'fa-phone-square' => '',
					'fa-twitter' => '',
					'fa-facebook' => '',
					'fa-github' => '',
					'fa-unlock' => '',
					'fa-credit-card' => '',
					'fa-rss' => '',
					'fa-hdd-o' => '',
					'fa-bullhorn' => '',
					'fa-bell' => '',
					'fa-certificate' => '',
					'fa-hand-o-right' => '',
					'fa-hand-o-left' => '',
					'fa-hand-o-up' => '',
					'fa-hand-o-down' => '',
					'fa-arrow-circle-left' => '',
					'fa-arrow-circle-right' => '',
					'fa-arrow-circle-up' => '',
					'fa-arrow-circle-down' => '',
					'fa-globe' => '',
					'fa-wrench' => '',
					'fa-tasks' => '',
					'fa-filter' => '',
					'fa-briefcase' => '',
					'fa-arrows-alt' => '',
					'fa-users' => '',
					'fa-link' => '',
					'fa-cloud' => '',
					'fa-flask' => '',
					'fa-scissors' => '',
					'fa-files-o' => '',
					'fa-paperclip' => '',
					'fa-floppy-o' => '',
					'fa-square' => '',
					'fa-bars' => '',
					'fa-list-ul' => '',
					'fa-list-ol' => '',
					'fa-strikethrough' => '',
					'fa-underline' => '',
					'fa-table' => '',
					'fa-magic' => '',
					'fa-truck' => '',
					'fa-pinterest' => '',
					'fa-pinterest-square' => '',
					'fa-google-plus-square' => '',
					'fa-google-plus' => '',
					'fa-money' => '',
					'fa-caret-down' => '',
					'fa-caret-up' => '',
					'fa-caret-left' => '',
					'fa-caret-right' => '',
					'fa-columns' => '',
					'fa-sort' => '',
					'fa-sort-asc' => '',
					'fa-sort-desc' => '',
					'fa-envelope' => '',
					'fa-linkedin' => '',
					'fa-undo' => '',
					'fa-gavel' => '',
					'fa-tachometer' => '',
					'fa-comment-o' => '',
					'fa-comments-o' => '',
					'fa-bolt' => '',
					'fa-sitemap' => '',
					'fa-umbrella' => '',
					'fa-clipboard' => '',
					'fa-lightbulb-o' => '',
					'fa-exchange' => '',
					'fa-cloud-download' => '',
					'fa-cloud-upload' => '',
					'fa-user-md' => '',
					'fa-stethoscope' => '',
					'fa-suitcase' => '',
					'fa-bell-o' => '',
					'fa-coffee' => '',
					'fa-cutlery' => '',
					'fa-file-text-o' => '',
					'fa-building-o' => '',
					'fa-hospital-o' => '',
					'fa-ambulance' => '',
					'fa-medkit' => '',
					'fa-fighter-jet' => '',
					'fa-beer' => '',
					'fa-h-square' => '',
					'fa-plus-square' => '',
					'fa-angle-double-left' => '',
					'fa-angle-double-right' => '',
					'fa-angle-double-up' => '',
					'fa-angle-double-down' => '',
					'fa-angle-left' => '',
					'fa-angle-right' => '',
					'fa-angle-up' => '',
					'fa-angle-down' => '',
					'fa-desktop' => '',
					'fa-laptop' => '',
					'fa-tablet' => '',
					'fa-mobile' => '',
					'fa-circle-o' => '',
					'fa-quote-left' => '',
					'fa-quote-right' => '',
					'fa-spinner' => '',
					'fa-circle' => '',
					'fa-reply' => '',
					'fa-github-alt' => '',
					'fa-folder-o' => '',
					'fa-folder-open-o' => '',
					'fa-smile-o' => '',
					'fa-frown-o' => '',
					'fa-meh-o' => '',
					'fa-gamepad' => '',
					'fa-keyboard-o' => '',
					'fa-flag-o' => '',
					'fa-flag-checkered' => '',
					'fa-terminal' => '',
					'fa-code' => '',
					'fa-reply-all' => '',
					'fa-mail-reply-all' => '',
					'fa-star-half-o' => '',
					'fa-location-arrow' => '',
					'fa-crop' => '',
					'fa-code-fork' => '',
					'fa-chain-broken' => '',
					'fa-question' => '',
					'fa-info' => '',
					'fa-exclamation' => '',
					'fa-superscript' => '',
					'fa-subscript' => '',
					'fa-eraser' => '',
					'fa-puzzle-piece' => '',
					'fa-microphone' => '',
					'fa-microphone-slash' => '',
					'fa-shield' => '',
					'fa-calendar-o' => '',
					'fa-fire-extinguisher' => '',
					'fa-rocket' => '',
					'fa-maxcdn' => '',
					'fa-chevron-circle-left' => '',
					'fa-chevron-circle-right' => '',
					'fa-chevron-circle-up' => '',
					'fa-chevron-circle-down' => '',
					'fa-html5' => '',
					'fa-css3' => '',
					'fa-anchor' => '',
					'fa-unlock-alt' => '',
					'fa-bullseye' => '',
					'fa-ellipsis-h' => '',
					'fa-ellipsis-v' => '',
					'fa-rss-square' => '',
					'fa-play-circle' => '',
					'fa-ticket' => '',
					'fa-minus-square' => '',
					'fa-minus-square-o' => '',
					'fa-level-up' => '',
					'fa-level-down' => '',
					'fa-check-square' => '',
					'fa-pencil-square' => '',
					'fa-external-link-square' => '',
					'fa-share-square' => '',
					'fa-compass' => '',
					'fa-caret-square-o-down' => '',
					'fa-caret-square-o-up' => '',
					'fa-caret-square-o-right' => '',
					'fa-eur' => '',
					'fa-gbp' => '',
					'fa-usd' => '',
					'fa-inr' => '',
					'fa-jpy' => '',
					'fa-rub' => '',
					'fa-krw' => '',
					'fa-btc' => '',
					'fa-file' => '',
					'fa-file-text' => '',
					'fa-sort-alpha-asc' => '',
					'fa-sort-alpha-desc' => '',
					'fa-sort-amount-asc' => '',
					'fa-sort-amount-desc' => '',
					'fa-sort-numeric-asc' => '',
					'fa-sort-numeric-desc' => '',
					'fa-thumbs-up' => '',
					'fa-thumbs-down' => '',
					'fa-youtube-square' => '',
					'fa-youtube' => '',
					'fa-xing' => '',
					'fa-xing-square' => '',
					'fa-youtube-play' => '',
					'fa-dropbox' => '',
					'fa-stack-overflow' => '',
					'fa-instagram' => '',
					'fa-flickr' => '',
					'fa-adn' => '',
					'fa-bitbucket' => '',
					'fa-bitbucket-square' => '',
					'fa-tumblr' => '',
					'fa-tumblr-square' => '',
					'fa-long-arrow-down' => '',
					'fa-long-arrow-up' => '',
					'fa-long-arrow-left' => '',
					'fa-long-arrow-right' => '',
					'fa-apple' => '',
					'fa-windows' => '',
					'fa-android' => '',
					'fa-linux' => '',
					'fa-dribbble' => '',
					'fa-skype' => '',
					'fa-foursquare' => '',
					'fa-trello' => '',
					'fa-female' => '',
					'fa-male' => '',
					'fa-gittip' => '',
					'fa-sun-o' => '',
					'fa-moon-o' => '',
					'fa-archive' => '',
					'fa-bug' => '',
					'fa-vk' => '',
					'fa-weibo' => '',
					'fa-renren' => '',
					'fa-pagelines' => '',
					'fa-stack-exchange' => '',
					'fa-arrow-circle-o-right' => '',
					'fa-arrow-circle-o-left' => '',
					'fa-caret-square-o-left' => '',
					'fa-dot-circle-o' => '',
					'fa-wheelchair' => '',
					'fa-vimeo-square' => '',
					'fa-try' => '',
					'fa-plus-square-o' => '',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53d11b1f44b93',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Add an image for service.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53d11a22246ee',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_53d11b50e5c99',
				'label' => 'Link',
				'name' => 'link',
				'type' => 'text',
				'instructions' => 'Add service link.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'service_post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_titled-slider',
		'title' => 'Titled Slider',
		'fields' => array (
			array (
				'key' => 'field_54425102f5251',
				'label' => 'TSlider',
				'name' => 'tslider',
				'type' => 'repeater',
				'instructions' => 'Add slider items.',
				'sub_fields' => array (
					array (
						'key' => 'field_544251afac0ec',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => 'Add title.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_544251c1ac0ed',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'wysiwyg',
						'instructions' => 'Add content to display on left side.',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_544251f0ac0ee',
						'label' => 'Image Display',
						'name' => 'image_display',
						'type' => 'radio',
						'instructions' => 'Choose if you want row or column display for images (default is row).',
						'column_width' => '',
						'choices' => array (
							'row' => 'row',
							'col' => 'col',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'row',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_544252a583c06',
						'label' => 'Image1',
						'name' => 'image1',
						'type' => 'image',
						'instructions' => 'Choose first image.',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array (
						'key' => 'field_544252ba83c07',
						'label' => 'Image1 Link',
						'name' => 'image1_link',
						'type' => 'text',
						'instructions' => 'Add a link for image1.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_544252cf83c08',
						'label' => 'Image2',
						'name' => 'image2',
						'type' => 'image',
						'instructions' => 'Choose second image.',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array (
						'key' => 'field_544252eb83c09',
						'label' => 'Image2 Link',
						'name' => 'image2_link',
						'type' => 'text',
						'instructions' => 'Add a link for image2.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template_titledSlider.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
}
